replicaCount: 2

image:
  repository: qr-code-api
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  name: "qr-code-api"
  annotations: {} # This will be populated by ArgoCD or manually with the Role ARN

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.qr-code.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  awsRegion: "us-east-1"
  s3EndpointUrl: ""
  s3BucketName: "" # Make this configurable
